/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.4.6. DO NOT MODIFY.
*/
`timescale 100fs/100fs
module system
    ( // Inputs
      input  clk // clock
    , input  rst // reset
    , input  en // enable
    , input [7:0] data_in

      // Outputs
    , output wire [7:0] after_n
    );
  // Clash.hs:12:1-7
  reg [7:0] s = 8'd0;

  assign after_n = (s * 8'd13) % 8'd17;

  // register begin
  always @(posedge clk or  posedge  rst) begin : s_register
    if ( rst) begin
      s <= 8'd0;
    end else if (en) begin
      s <= data_in;
    end
  end
  // register end


endmodule

